---

- hosts: tag_Name_bot
  vars_files:
    - vars/secrets.yml
  become: True
  handlers:
    # for every bot name, you need a custom bot handler
    - name: restart hal
      service: >
        name=hal
        state=restarted
    - name: restart jarvis
      service: >
        name=jarvis
        state=restarted
  roles:
    - role: nodejs_6
      tags: nodejs
    - role: redis
      tags: redis
    - role: mysql_server
      tags: mysql
    - role: hubot
      name: hal
      adapter: slack
      log_level: debug
      tags:
        - hubot
        - hal
    - role: hal
      tags: hal
    - role: hubot
      name: jarvis
      adapter: slack
      port: 8081
      tags:
        - hubot
        - jarvis
    - role: jarvis
      tags: jarvis
  post_tasks:
    - name: start services
      service: >
        name="{{ item }}"
        state=started
      with_items:
        - redis
        - hal
        - jarvis
        - mysqld
