---

- name: creating vpc
  ec2_vpc:
    profile: hubot
    region: "{{ aws_region }}"
    state: present
    cidr_block: 10.10.0.0/16
    resource_tags:
      Name: "{{ project_name }}"
    subnets:
      - cidr: 10.10.1.0/24
        az: "{{ aws_az }}"
        resource_tags: { "Name" : "{{ project_name }}_{{ aws_az }}" }
    internet_gateway: True
    route_tables:
      - subnets:
        - 10.10.1.0/24
        routes:
          - dest: 0.0.0.0/0
            gw: igw
        resource_tags:
          Name: "{{ project_name }}"
  register: aws_vpc
