---

- name: rsync scripts
  synchronize: >
    src="{{ playbook_dir }}/roles/bot/files/scripts/"
    dest=/opt/hubot/scripts/
    checksum=yes
    recursive=yes
    delete=yes
    owner=no
    group=no
    times=no
    rsync_opts="--exclude .git* --exclude .DS_Store*"
  notify: restart hubot
  become_user: hubot
