---

- name: add hubot group
  group: >
    name="{{ name }}"
    state=present

- name: add hubot user
  user: >
    name="{{ name }}"
    group="{{ name }}"
    home="/opt/{{ name }}"
    state=present

- name: install coffee-script
  npm: >
    name=coffee-script
    global=True

- name: install hubot and slack adapter
  npm: >
    name={{ item }}
    path="/opt/{{ name }}"
  become_user: "{{ name }}"
  with_items:
    - hubot
    - hubot-slack
    - mysql

- name: config DIRs /opt/<name>
  file: >
    path="/opt/{{ name }}/{{ item }}"
    state=directory
    owner="{{ name }}"
    group="{{ name }}"
    mode=0755
  with_items:
    - bin
    - scripts

- name: config /etc/init.d/<name>
  template: >
    src=initd_hubot
    dest="/etc/init.d/{{ name }}"
    owner=root
    group=root
    mode=0755

- name: config /opt/hubot/*
  template: >
    src="{{ item }}"
    dest="/opt/{{ name }}/{{ item }}"
    owner="{{ name }}"
    group="{{ name }}"
    mode=0644
  notify: restart hal
  with_items:
    - hubot.env

- name: config /opt/<name>/bin/hubot.sh
  template: >
    src=hubot.sh
    dest="/opt/{{ name }}/bin/hubot.sh"
    owner="{{ name }}"
    group="{{ name }}"
    mode=0755
  notify: restart hal

- name: enable hubot service
  service: >
    name="{{ name }}"
    enabled=True
    
