---

- name: key pair
  ec2_key:
    profile: hubot
    region: "{{ aws_region }}"
    state: present
    name: "{{ project_name }}"
    key_material: "{{ item }}"
  with_file: custom_rsa.pub
  register: aws_key_pairs
  
