---

- name: rsync scripts
  synchronize: >
    src="{{ playbook_dir }}/roles/hal/files/scripts/"
    dest=/opt/hal/scripts/
    checksum=yes
    recursive=yes
    delete=yes
    owner=no
    group=no
    times=no
    rsync_opts="--exclude .git* --exclude .DS_Store*"
  notify: restart hal
  become_user: hal
